export const INITIAL_EMPLOYEES = [
  // Super Admin
  {
    id: 'emp-001',
    employeeId: 'SA-001',
    firstName: 'Alex',
    lastName: 'Morgan',
    email: 'admin@hrms.com',
    phone: '+1 (555) 019-2831',
    gender: 'Female',
    dateOfBirth: '1988-06-12',
    profilePhoto: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    address: '500 Howard St, San Francisco, CA',
    role: 'SUPER_ADMIN',
    organizationId: 'org-001',
    organizationName: 'Acme Global Technologies',
    managerId: null,
    managerName: null,
    department: 'Executive Board',
    designation: 'Chief System Administrator',
    joiningDate: '2020-01-15',
    employmentType: 'Full-Time',
    employmentStatus: 'ACTIVE',
    createdAt: '2020-01-15T08:00:00.000Z'
  },
  // Manager 1 (Acme Global Technologies)
  {
    id: 'emp-101',
    employeeId: 'MGR-101',
    firstName: 'Sarah',
    lastName: 'Jenkins',
    email: 'sarah.jenkins@acmeglobal.com',
    phone: '+1 (555) 301-4492',
    gender: 'Female',
    dateOfBirth: '1990-03-24',
    profilePhoto: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    address: '124 Market St, San Francisco, CA',
    role: 'MANAGER',
    organizationId: 'org-001',
    organizationName: 'Acme Global Technologies',
    managerId: null,
    managerName: null,
    department: 'Engineering',
    designation: 'Engineering Director',
    joiningDate: '2021-03-15',
    employmentType: 'Full-Time',
    employmentStatus: 'ACTIVE',
    createdAt: '2021-03-15T09:00:00.000Z'
  },
  // Team Employees under Manager 1 (Sarah Jenkins)
  {
    id: 'emp-102',
    employeeId: 'EMP-102',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@acmeglobal.com',
    phone: '+1 (555) 819-2049',
    gender: 'Male',
    dateOfBirth: '1994-08-19',
    profilePhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    address: '742 Evergreen Terrace, San Francisco, CA',
    role: 'EMPLOYEE',
    organizationId: 'org-001',
    organizationName: 'Acme Global Technologies',
    managerId: 'emp-101',
    managerName: 'Sarah Jenkins',
    department: 'Engineering',
    designation: 'Senior Frontend Developer',
    joiningDate: '2022-06-01',
    employmentType: 'Full-Time',
    employmentStatus: 'ACTIVE',
    createdAt: '2022-06-01T10:00:00.000Z'
  },
  {
    id: 'emp-103',
    employeeId: 'EMP-103',
    firstName: 'Emily',
    lastName: 'Watson',
    email: 'emily.watson@acmeglobal.com',
    phone: '+1 (555) 912-3847',
    gender: 'Female',
    dateOfBirth: '1996-11-05',
    profilePhoto: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    address: '88 King St, San Francisco, CA',
    role: 'EMPLOYEE',
    organizationId: 'org-001',
    organizationName: 'Acme Global Technologies',
    managerId: 'emp-101',
    managerName: 'Sarah Jenkins',
    department: 'Engineering',
    designation: 'Full Stack Engineer',
    joiningDate: '2023-02-15',
    employmentType: 'Full-Time',
    employmentStatus: 'ACTIVE',
    createdAt: '2023-02-15T08:30:00.000Z'
  },
  {
    id: 'emp-104',
    employeeId: 'EMP-104',
    firstName: 'Alex',
    lastName: 'Chen',
    email: 'alex.chen@acmeglobal.com',
    phone: '+1 (555) 482-1920',
    gender: 'Male',
    dateOfBirth: '1993-01-14',
    profilePhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    address: '350 Mission St, San Francisco, CA',
    role: 'EMPLOYEE',
    organizationId: 'org-001',
    organizationName: 'Acme Global Technologies',
    managerId: 'emp-101',
    managerName: 'Sarah Jenkins',
    department: 'Engineering',
    designation: 'DevOps & QA Lead',
    joiningDate: '2023-07-10',
    employmentType: 'Full-Time',
    employmentStatus: 'ACTIVE',
    createdAt: '2023-07-10T09:15:00.000Z'
  },
  // Manager 2 (Nexus Health Systems)
  {
    id: 'emp-201',
    employeeId: 'MGR-201',
    firstName: 'David',
    lastName: 'Ross',
    email: 'david.ross@nexushealth.org',
    phone: '+44 20 7946 0888',
    gender: 'Male',
    dateOfBirth: '1987-09-30',
    profilePhoto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    address: '15 Baker Street, London, UK',
    role: 'MANAGER',
    organizationId: 'org-002',
    organizationName: 'Nexus Health Systems',
    managerId: null,
    managerName: null,
    department: 'Clinical Operations',
    designation: 'VP of Medical Operations',
    joiningDate: '2022-01-10',
    employmentType: 'Full-Time',
    employmentStatus: 'ACTIVE',
    createdAt: '2022-01-10T10:00:00.000Z'
  },
  // Team Employees under Manager 2 (David Ross)
  {
    id: 'emp-202',
    employeeId: 'EMP-202',
    firstName: 'Michael',
    lastName: 'Chang',
    email: 'michael.chang@nexushealth.org',
    phone: '+44 20 7946 0555',
    gender: 'Male',
    dateOfBirth: '1995-04-18',
    profilePhoto: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    address: '42 Oxford St, London, UK',
    role: 'EMPLOYEE',
    organizationId: 'org-002',
    organizationName: 'Nexus Health Systems',
    managerId: 'emp-201',
    managerName: 'David Ross',
    department: 'Clinical Operations',
    designation: 'Health Data Analyst',
    joiningDate: '2023-05-20',
    employmentType: 'Full-Time',
    employmentStatus: 'ACTIVE',
    createdAt: '2023-05-20T11:00:00.000Z'
  },
  {
    id: 'emp-203',
    employeeId: 'EMP-203',
    firstName: 'Lisa',
    lastName: 'Ray',
    email: 'lisa.ray@nexushealth.org',
    phone: '+44 20 7946 0777',
    gender: 'Female',
    dateOfBirth: '1997-12-01',
    profilePhoto: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    address: '10 Regent St, London, UK',
    role: 'EMPLOYEE',
    organizationId: 'org-002',
    organizationName: 'Nexus Health Systems',
    managerId: 'emp-201',
    managerName: 'David Ross',
    department: 'Clinical Operations',
    designation: 'Telehealth Coordinator',
    joiningDate: '2023-11-01',
    employmentType: 'Full-Time',
    employmentStatus: 'INACTIVE', // Example inactive record for soft deletion test
    createdAt: '2023-11-01T09:00:00.000Z'
  }
];

export const DEPARTMENT_OPTIONS = [
  'Engineering',
  'Clinical Operations',
  'Product & Design',
  'Human Resources',
  'Finance & Accounting',
  'Sales & Marketing',
  'Customer Success',
  'Legal & Compliance'
];

export const EMPLOYMENT_TYPE_OPTIONS = [
  'Full-Time',
  'Part-Time',
  'Contract',
  'Internship'
];
