export const INITIAL_ORGANIZATIONS = [
  {
    id: 'org-001',
    logo: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=120&auto=format&fit=crop&q=80',
    name: 'Acme Global Technologies',
    code: 'ACME-TECH',
    type: 'Enterprise',
    industry: 'Information Technology',
    description: 'Leading provider of enterprise cloud infrastructure and AI-driven software solutions globally.',
    email: 'contact@acmeglobal.com',
    phone: '+1 (555) 234-5678',
    alternatePhone: '+1 (555) 234-5679',
    website: 'https://acmeglobal.tech',
    addressLine1: '100 Innovation Way',
    addressLine2: 'Suite 400',
    city: 'San Francisco',
    state: 'California',
    country: 'United States',
    postalCode: '94105',
    registrationNumber: 'REG-2015-88492',
    taxId: 'US-99-4820193',
    establishedDate: '2015-04-15',
    timezone: 'America/Los_Angeles (UTC-07:00)',
    currency: 'USD ($)',
    dateFormat: 'YYYY-MM-DD',
    status: 'Active',
    createdAt: '2023-01-10T08:30:00.000Z'
  },
  {
    id: 'org-002',
    logo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=120&auto=format&fit=crop&q=80',
    name: 'Nexus Health Systems',
    code: 'NEXUS-HLTH',
    type: 'Enterprise',
    industry: 'Healthcare',
    description: 'Pioneering digital healthcare network delivering telehealth and modern medical diagnostics.',
    email: 'info@nexushealth.org',
    phone: '+44 20 7946 0912',
    alternatePhone: '+44 20 7946 0913',
    website: 'https://nexushealth.org',
    addressLine1: '45 Harley Street',
    addressLine2: 'Medical Wing B',
    city: 'London',
    state: 'Greater London',
    country: 'United Kingdom',
    postalCode: 'W1G 8Q1',
    registrationNumber: 'UK-8940217',
    taxId: 'GB-334902184',
    establishedDate: '2018-09-20',
    timezone: 'Europe/London (UTC+01:00)',
    currency: 'GBP (£)',
    dateFormat: 'DD/MM/YYYY',
    status: 'Active',
    createdAt: '2023-03-22T10:15:00.000Z'
  },
  {
    id: 'org-003',
    logo: 'https://images.unsplash.com/photo-1554469384-e58fac16e23a?w=120&auto=format&fit=crop&q=80',
    name: 'Horizon Financial Group',
    code: 'HORIZON-FIN',
    type: 'Subsidiary',
    industry: 'Financial Services',
    description: 'Premier wealth management, corporate advisory, and investment banking services firm.',
    email: 'corporate@horizonfin.com',
    phone: '+1 (212) 555-0198',
    alternatePhone: '',
    website: 'https://horizonfinancial.com',
    addressLine1: '250 Wall Street',
    addressLine2: 'Floor 18',
    city: 'New York',
    state: 'New York',
    country: 'United States',
    postalCode: '10005',
    registrationNumber: 'REG-NY-392019',
    taxId: 'US-12-8493021',
    establishedDate: '2012-11-05',
    timezone: 'America/New_York (UTC-04:00)',
    currency: 'USD ($)',
    dateFormat: 'MM/DD/YYYY',
    status: 'Active',
    createdAt: '2023-05-14T14:20:00.000Z'
  },
  {
    id: 'org-004',
    logo: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?w=120&auto=format&fit=crop&q=80',
    name: 'Vanguard Logistics & Supply',
    code: 'VANG-LOG',
    type: 'Branch',
    industry: 'Logistics & Supply Chain',
    description: 'Global freight forwarding, warehouse automation, and end-to-end supply chain management.',
    email: 'operations@vanguardlog.de',
    phone: '+49 30 12345678',
    alternatePhone: '+49 30 12345679',
    website: 'https://vanguardlogistics.de',
    addressLine1: 'Hafenstrasse 12',
    addressLine2: 'Gebäude A',
    city: 'Hamburg',
    state: 'Hamburg',
    country: 'Germany',
    postalCode: '20457',
    registrationNumber: 'HRB-104928',
    taxId: 'DE-812394857',
    establishedDate: '2016-03-10',
    timezone: 'Europe/Berlin (UTC+02:00)',
    currency: 'EUR (€)',
    dateFormat: 'DD/MM/YYYY',
    status: 'Inactive',
    createdAt: '2023-08-01T11:45:00.000Z'
  },
  {
    id: 'org-005',
    logo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=120&auto=format&fit=crop&q=80',
    name: 'EcoEnergy Dynamics',
    code: 'ECO-ENERGY',
    type: 'Startup',
    industry: 'Clean Energy & Utilities',
    description: 'Innovative clean-tech enterprise specializing in solar grid storage and wind farm optimization.',
    email: 'contact@ecoenergy.io',
    phone: '+91 80 4112 9000',
    alternatePhone: '+91 80 4112 9001',
    website: 'https://ecoenergy.io',
    addressLine1: 'Outer Ring Road, Marathahalli',
    addressLine2: 'Tech Park Tower 3',
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    postalCode: '560103',
    registrationNumber: 'CIN-U74999KA2020PTC139021',
    taxId: '29AAACE9402R1Z5',
    establishedDate: '2020-08-14',
    timezone: 'Asia/Kolkata (UTC+05:30)',
    currency: 'INR (₹)',
    dateFormat: 'DD/MM/YYYY',
    status: 'Active',
    createdAt: '2023-09-18T09:00:00.000Z'
  }
];

export const INDUSTRY_OPTIONS = [
  'Information Technology',
  'Healthcare',
  'Financial Services',
  'Logistics & Supply Chain',
  'Clean Energy & Utilities',
  'Education',
  'Manufacturing',
  'Retail & E-commerce',
  'Telecommunications',
  'Real Estate & Construction'
];

export const TYPE_OPTIONS = [
  'Enterprise',
  'Subsidiary',
  'Branch',
  'Startup',
  'Non-Profit',
  'Government Entity'
];

export const TIMEZONE_OPTIONS = [
  'America/Los_Angeles (UTC-07:00)',
  'America/New_York (UTC-04:00)',
  'Europe/London (UTC+01:00)',
  'Europe/Berlin (UTC+02:00)',
  'Asia/Kolkata (UTC+05:30)',
  'Asia/Singapore (UTC+08:00)',
  'Australia/Sydney (UTC+10:00)'
];

export const CURRENCY_OPTIONS = [
  'USD ($)',
  'EUR (€)',
  'GBP (£)',
  'INR (₹)',
  'CAD ($)',
  'AUD ($)',
  'SGD ($)'
];

export const DATE_FORMAT_OPTIONS = [
  'YYYY-MM-DD',
  'DD/MM/YYYY',
  'MM/DD/YYYY',
  'DD-MMM-YYYY'
];
